name: SonarCloud Analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Gui-Kol_Paw-Fight
            -Dsonar.organization=SEU_ORG
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
